apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnet-sample-ingress
  namespace: aspnet-sample
spec:
  ingressClassName: nginx
  rules:
  - host: test.1kb.uz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aspnet-sample
            port:
              number: 80
